services:
  trainer-db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env

  trainer-api:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - trainer-db
